# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yerkontrolis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 30, 571, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sekiz_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sekiz_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.sekiz_tusu.setObjectName("sekiz_tusu")
        self.gridLayout.addWidget(self.sekiz_tusu, 9, 2, 1, 1)
        self.bes_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bes_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.bes_tusu.setObjectName("bes_tusu")
        self.gridLayout.addWidget(self.bes_tusu, 7, 2, 1, 1)
        self.dort_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dort_tusu.setStyleSheet("\n"
"background-color: rgb(243, 137, 229);")
        self.dort_tusu.setObjectName("dort_tusu")
        self.gridLayout.addWidget(self.dort_tusu, 7, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 4, 1, 1)
        self.yedi_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.yedi_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.yedi_tusu.setObjectName("yedi_tusu")
        self.gridLayout.addWidget(self.yedi_tusu, 9, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 15, 4, 1, 1)
        self.alti_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.alti_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.alti_tusu.setObjectName("alti_tusu")
        self.gridLayout.addWidget(self.alti_tusu, 7, 3, 1, 1)
        self.sifir_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sifir_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.sifir_tusu.setObjectName("sifir_tusu")
        self.gridLayout.addWidget(self.sifir_tusu, 12, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 3, 1, 1)
        self.bolme_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bolme_tusu.setStyleSheet("background-color: rgb(64, 67, 191);\n"
"")
        self.bolme_tusu.setAutoRepeatInterval(100)
        self.bolme_tusu.setObjectName("bolme_tusu")
        self.gridLayout.addWidget(self.bolme_tusu, 12, 1, 1, 1)
        self.carpma_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.carpma_tusu.setStyleSheet("\n"
"background-color: rgb(64, 67, 191);")
        self.carpma_tusu.setObjectName("carpma_tusu")
        self.gridLayout.addWidget(self.carpma_tusu, 12, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.dokuz_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dokuz_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.dokuz_tusu.setObjectName("dokuz_tusu")
        self.gridLayout.addWidget(self.dokuz_tusu, 9, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 9, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sekiz_tusu.setText(_translate("MainWindow", "GUIDED"))
        self.bes_tusu.setText(_translate("MainWindow", "DISARM"))
        self.dort_tusu.setText(_translate("MainWindow", "ARM"))
        self.yedi_tusu.setText(_translate("MainWindow", "LOITER"))
        self.alti_tusu.setText(_translate("MainWindow", "RTL"))
        self.sifir_tusu.setText(_translate("MainWindow", "LAND"))
        self.bolme_tusu.setText(_translate("MainWindow", "TAKEOFF"))
        self.carpma_tusu.setText(_translate("MainWindow", "GOREV"))
        self.dokuz_tusu.setText(_translate("MainWindow", "STABILIZE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
